name: Dependent Workflow

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Job1 Workflow
        run: |
          echo "Hello, Job1 Workflow!"

  job-2:
    runs-on: ubuntu-latest
    needs: [job-1]

    steps:
      - name: Job2 Workflow
        run: |
          echo "Hello, Job2 Workflow!"

  job-3:
    runs-on: ubuntu-latest
    needs: [job-1, job-2]

    steps:
      - name: Job3 Workflow
        run: |
          echo "Hello, Job3 Workflow!"
